import { searchHelloFresh } from './hellofreshDatabase';

// Curated common foods with reliable calorie data (per 100g unless noted)
// servings: named portion presets shown as quick-pick buttons in the UI
export const COMMON_FOODS = [
  // Proteins
  { name: 'HF Greek Salad with Spiced Pork Patties', caloriesPer100g: 150, category: 'Meals', brand: 'HelloFresh', servings: [{ label: '1 serving', g: 400 }] },
  { name: 'HF Mexican-Style Cheesy Chicken Tortas', caloriesPer100g: 175, category: 'Meals', brand: 'HelloFresh', servings: [{ label: '1 serving', g: 400 }] },
  { name: 'HF Chicken & Crispy Prosciutto Caesar Salad', caloriesPer100g: 140, category: 'Meals', brand: 'HelloFresh', servings: [{ label: '1 serving', g: 400 }] },
  { name: 'HF Sesame-Soy Pork Bowls', caloriesPer100g: 254, category: 'Meals', brand: 'HelloFresh', servings: [{ label: '1 serving', g: 500 }] },
  { name: 'Costco Chicken Pot Pie', caloriesPer100g: 300, category: 'Meals', brand: 'Costco', servings: [{ label: '1 serving', g: 100 }, { label: '2 servings', g: 200 }] },
  { name: 'Chicken and Dumplings', caloriesPer100g: 118, category: 'Meals', servings: [{ label: '1 cup', g: 245 }, { label: '1.5 cups', g: 368 }] },
  { name: 'Birthday Cake', caloriesPer100g: 371, category: 'Sweets', servings: [{ label: '1 slice', g: 80 }, { label: '2 slices', g: 160 }] },
  { name: 'Designer Whey Gourmet Chocolate', caloriesPer100g: 355, category: 'Proteins', brand: 'Designer Wellness', servings: [{ label: '2 scoops', g: 31 }, { label: '4 scoops', g: 62 }] },
  { name: 'Chicken Breast (cooked)', caloriesPer100g: 165, category: 'Proteins', servings: [{ label: '3 oz', g: 85 }, { label: '4 oz', g: 113 }, { label: '6 oz', g: 170 }] },
  { name: 'Chicken Thigh (cooked)', caloriesPer100g: 209, category: 'Proteins', servings: [{ label: '1 thigh', g: 85 }, { label: '2 thighs', g: 170 }] },
  { name: 'Ground Beef 80/20 (cooked)', caloriesPer100g: 254, category: 'Proteins', servings: [{ label: '3 oz', g: 85 }, { label: '4 oz', g: 113 }] },
  { name: 'Ground Beef 93/7 (cooked)', caloriesPer100g: 218, category: 'Proteins', servings: [{ label: '3 oz', g: 85 }, { label: '4 oz', g: 113 }] },
  { name: 'Salmon (cooked)', caloriesPer100g: 208, category: 'Proteins', servings: [{ label: '3 oz', g: 85 }, { label: '6 oz', g: 170 }] },
  { name: 'Tuna (canned in water)', caloriesPer100g: 116, category: 'Proteins', servings: [{ label: '½ can', g: 85 }, { label: '1 can', g: 170 }] },
  { name: 'Shrimp (cooked)', caloriesPer100g: 99, category: 'Proteins', servings: [{ label: '3 oz', g: 85 }, { label: '6 oz', g: 170 }] },
  { name: 'Tilapia (cooked)', caloriesPer100g: 128, category: 'Proteins', servings: [{ label: '1 fillet', g: 87 }] },
  { name: 'Pork Chop (cooked)', caloriesPer100g: 231, category: 'Proteins', servings: [{ label: '1 chop', g: 113 }] },
  { name: 'Turkey Breast (cooked)', caloriesPer100g: 135, category: 'Proteins', servings: [{ label: '3 oz', g: 85 }] },
  { name: 'Bacon (cooked)', caloriesPer100g: 541, category: 'Proteins', servings: [{ label: '1 slice', g: 8 }, { label: '2 slices', g: 16 }, { label: '3 slices', g: 24 }] },
  { name: 'Egg (whole, large)', caloriesPer100g: 143, category: 'Proteins', servings: [{ label: '1 egg', g: 50 }, { label: '2 eggs', g: 100 }, { label: '3 eggs', g: 150 }] },
  { name: 'Egg White', caloriesPer100g: 52, category: 'Proteins', servings: [{ label: '1 white', g: 33 }, { label: '2 whites', g: 66 }] },
  { name: 'Greek Yogurt (plain, 0%)', caloriesPer100g: 59, category: 'Dairy', servings: [{ label: '½ cup', g: 113 }, { label: '1 cup', g: 227 }] },
  { name: 'Greek Yogurt (plain, 2%)', caloriesPer100g: 73, category: 'Dairy', servings: [{ label: '½ cup', g: 113 }, { label: '1 cup', g: 227 }] },
  { name: 'Cottage Cheese (1%)', caloriesPer100g: 72, category: 'Dairy', servings: [{ label: '½ cup', g: 113 }, { label: '1 cup', g: 226 }] },
  { name: 'Cottage Cheese (4%)', caloriesPer100g: 98, category: 'Dairy', servings: [{ label: '½ cup', g: 113 }, { label: '1 cup', g: 226 }] },
  { name: 'Black Beans (cooked)', caloriesPer100g: 132, category: 'Proteins', servings: [{ label: '½ cup', g: 86 }, { label: '1 cup', g: 172 }] },
  { name: 'Chickpeas (cooked)', caloriesPer100g: 164, category: 'Proteins', servings: [{ label: '½ cup', g: 82 }, { label: '1 cup', g: 164 }] },
  { name: 'Lentils (cooked)', caloriesPer100g: 116, category: 'Proteins', servings: [{ label: '½ cup', g: 99 }, { label: '1 cup', g: 198 }] },
  { name: 'Edamame', caloriesPer100g: 122, category: 'Proteins', servings: [{ label: '½ cup', g: 78 }, { label: '1 cup', g: 155 }] },
  { name: 'Tofu (firm)', caloriesPer100g: 76, category: 'Proteins', servings: [{ label: '3 oz', g: 85 }, { label: '½ block', g: 170 }] },
  { name: 'Deli Turkey', caloriesPer100g: 104, category: 'Proteins', servings: [{ label: '1 slice', g: 28 }, { label: '2 slices', g: 56 }, { label: '4 slices', g: 113 }] },
  { name: 'Deli Ham', caloriesPer100g: 107, category: 'Proteins', servings: [{ label: '1 slice', g: 28 }, { label: '2 slices', g: 56 }] },

  // Dairy
  { name: 'Whole Milk', caloriesPer100g: 61, category: 'Dairy', servings: [{ label: '½ cup', g: 122 }, { label: '1 cup', g: 244 }] },
  { name: '2% Milk', caloriesPer100g: 50, category: 'Dairy', servings: [{ label: '½ cup', g: 122 }, { label: '1 cup', g: 244 }] },
  { name: 'Skim Milk', caloriesPer100g: 34, category: 'Dairy', servings: [{ label: '½ cup', g: 122 }, { label: '1 cup', g: 244 }] },
  { name: 'Cheddar Cheese', caloriesPer100g: 402, category: 'Dairy', servings: [{ label: '1 slice', g: 28 }, { label: '1 oz', g: 28 }, { label: '¼ cup shredded', g: 28 }] },
  { name: 'Mozzarella Cheese', caloriesPer100g: 280, category: 'Dairy', servings: [{ label: '1 oz', g: 28 }, { label: '¼ cup', g: 28 }] },
  { name: 'Parmesan Cheese', caloriesPer100g: 431, category: 'Dairy', servings: [{ label: '1 tbsp', g: 5 }, { label: '2 tbsp', g: 10 }] },
  { name: 'Cream Cheese', caloriesPer100g: 342, category: 'Dairy', servings: [{ label: '1 tbsp', g: 14 }, { label: '2 tbsp', g: 28 }] },
  { name: 'Butter', caloriesPer100g: 717, category: 'Fats & Oils', servings: [{ label: '1 tsp', g: 5 }, { label: '1 tbsp', g: 14 }] },
  { name: 'Yogurt (plain, whole)', caloriesPer100g: 61, category: 'Dairy', servings: [{ label: '½ cup', g: 113 }, { label: '1 cup', g: 227 }] },
  { name: 'Whey Protein Powder', caloriesPer100g: 400, category: 'Proteins', servings: [{ label: '1 scoop', g: 30 }] },

  // Grains
  { name: 'White Rice (cooked)', caloriesPer100g: 130, category: 'Grains', servings: [{ label: '½ cup', g: 93 }, { label: '1 cup', g: 186 }] },
  { name: 'Brown Rice (cooked)', caloriesPer100g: 123, category: 'Grains', servings: [{ label: '½ cup', g: 98 }, { label: '1 cup', g: 195 }] },
  { name: 'Oatmeal (cooked)', caloriesPer100g: 71, category: 'Grains', servings: [{ label: '½ cup', g: 117 }, { label: '1 cup', g: 234 }] },
  { name: 'Oats (dry)', caloriesPer100g: 389, category: 'Grains', servings: [{ label: '¼ cup', g: 20 }, { label: '½ cup', g: 40 }] },
  { name: 'White Bread', caloriesPer100g: 265, category: 'Grains', servings: [{ label: '1 slice', g: 28 }, { label: '2 slices', g: 56 }] },
  { name: 'Whole Wheat Bread', caloriesPer100g: 247, category: 'Grains', servings: [{ label: '1 slice', g: 30 }, { label: '2 slices', g: 60 }] },
  { name: 'Sourdough Bread', caloriesPer100g: 274, category: 'Grains', servings: [{ label: '1 slice', g: 35 }, { label: '2 slices', g: 70 }] },
  { name: 'Bagel (plain)', caloriesPer100g: 270, category: 'Grains', servings: [{ label: '1 bagel', g: 98 }, { label: '½ bagel', g: 49 }] },
  { name: 'English Muffin', caloriesPer100g: 227, category: 'Grains', servings: [{ label: '1 muffin', g: 57 }, { label: '½ muffin', g: 29 }] },
  { name: 'Pasta (cooked)', caloriesPer100g: 158, category: 'Grains', servings: [{ label: '½ cup', g: 70 }, { label: '1 cup', g: 140 }, { label: '2 cups', g: 280 }] },
  { name: 'Whole Wheat Pasta (cooked)', caloriesPer100g: 149, category: 'Grains', servings: [{ label: '½ cup', g: 70 }, { label: '1 cup', g: 140 }] },
  { name: 'Quinoa (cooked)', caloriesPer100g: 120, category: 'Grains', servings: [{ label: '½ cup', g: 93 }, { label: '1 cup', g: 185 }] },
  { name: 'Tortilla (flour, 10")', caloriesPer100g: 306, category: 'Grains', servings: [{ label: '1 tortilla', g: 72 }] },
  { name: 'Tortilla (corn, 6")', caloriesPer100g: 218, category: 'Grains', servings: [{ label: '1 tortilla', g: 26 }, { label: '2 tortillas', g: 52 }] },
  { name: 'Granola', caloriesPer100g: 471, category: 'Grains', servings: [{ label: '¼ cup', g: 30 }, { label: '½ cup', g: 60 }] },
  { name: 'Cereal (Cheerios)', caloriesPer100g: 375, category: 'Grains', servings: [{ label: '¾ cup', g: 28 }, { label: '1 cup', g: 37 }] },
  { name: 'Pancake (plain)', caloriesPer100g: 227, category: 'Grains', servings: [{ label: '1 pancake', g: 77 }, { label: '2 pancakes', g: 154 }] },
  { name: 'Waffle (plain)', caloriesPer100g: 291, category: 'Grains', servings: [{ label: '1 waffle', g: 75 }, { label: '2 waffles', g: 150 }] },
  { name: 'Crackers (saltine)', caloriesPer100g: 421, category: 'Grains', servings: [{ label: '5 crackers', g: 15 }, { label: '10 crackers', g: 30 }] },

  // Fruits & Vegetables
  { name: 'Banana', caloriesPer100g: 89, category: 'Fruits & Vegetables', servings: [{ label: 'small', g: 100 }, { label: 'medium', g: 120 }, { label: 'large', g: 140 }] },
  { name: 'Apple', caloriesPer100g: 52, category: 'Fruits & Vegetables', servings: [{ label: 'small', g: 149 }, { label: 'medium', g: 182 }, { label: 'large', g: 223 }] },
  { name: 'Orange', caloriesPer100g: 47, category: 'Fruits & Vegetables', servings: [{ label: 'medium', g: 131 }, { label: 'large', g: 184 }] },
  { name: 'Strawberries', caloriesPer100g: 32, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 76 }, { label: '1 cup', g: 152 }] },
  { name: 'Blueberries', caloriesPer100g: 57, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 74 }, { label: '1 cup', g: 148 }] },
  { name: 'Grapes', caloriesPer100g: 69, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 80 }, { label: '1 cup', g: 160 }] },
  { name: 'Watermelon', caloriesPer100g: 30, category: 'Fruits & Vegetables', servings: [{ label: '1 cup diced', g: 152 }, { label: '1 slice', g: 280 }] },
  { name: 'Mango', caloriesPer100g: 60, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 83 }, { label: '1 cup', g: 165 }] },
  { name: 'Pineapple', caloriesPer100g: 50, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 82 }, { label: '1 cup', g: 165 }] },
  { name: 'Avocado', caloriesPer100g: 160, category: 'Fruits & Vegetables', servings: [{ label: '¼ avocado', g: 50 }, { label: '½ avocado', g: 100 }, { label: '1 avocado', g: 200 }] },
  { name: 'Broccoli', caloriesPer100g: 34, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 46 }, { label: '1 cup', g: 91 }] },
  { name: 'Spinach', caloriesPer100g: 23, category: 'Fruits & Vegetables', servings: [{ label: '1 cup raw', g: 30 }, { label: '½ cup cooked', g: 90 }] },
  { name: 'Kale', caloriesPer100g: 49, category: 'Fruits & Vegetables', servings: [{ label: '1 cup raw', g: 67 }] },
  { name: 'Romaine Lettuce', caloriesPer100g: 17, category: 'Fruits & Vegetables', servings: [{ label: '1 cup', g: 47 }, { label: '2 cups', g: 94 }] },
  { name: 'Mixed Greens', caloriesPer100g: 20, category: 'Fruits & Vegetables', servings: [{ label: '1 cup', g: 40 }, { label: '2 cups', g: 80 }] },
  { name: 'Baby Carrots', caloriesPer100g: 35, category: 'Fruits & Vegetables', servings: [{ label: '10 carrots', g: 80 }, { label: '1 cup', g: 128 }] },
  { name: 'Celery', caloriesPer100g: 16, category: 'Fruits & Vegetables', servings: [{ label: '1 stalk', g: 40 }, { label: '1 cup', g: 101 }] },
  { name: 'Cucumber', caloriesPer100g: 15, category: 'Fruits & Vegetables', servings: [{ label: '½ cup sliced', g: 52 }, { label: '1 cup', g: 104 }] },
  { name: 'Bell Pepper', caloriesPer100g: 31, category: 'Fruits & Vegetables', servings: [{ label: '½ pepper', g: 75 }, { label: '1 pepper', g: 150 }] },
  { name: 'Tomato', caloriesPer100g: 18, category: 'Fruits & Vegetables', servings: [{ label: 'small', g: 91 }, { label: 'medium', g: 123 }] },
  { name: 'Cherry Tomatoes', caloriesPer100g: 18, category: 'Fruits & Vegetables', servings: [{ label: '5 tomatoes', g: 75 }, { label: '1 cup', g: 149 }] },
  { name: 'Sweet Potato (baked)', caloriesPer100g: 90, category: 'Fruits & Vegetables', servings: [{ label: 'small', g: 130 }, { label: 'medium', g: 180 }, { label: 'large', g: 230 }] },
  { name: 'Potato (baked)', caloriesPer100g: 93, category: 'Fruits & Vegetables', servings: [{ label: 'small', g: 138 }, { label: 'medium', g: 213 }, { label: 'large', g: 299 }] },
  { name: 'Corn (cooked)', caloriesPer100g: 96, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 77 }, { label: '1 ear', g: 90 }] },
  { name: 'Green Beans', caloriesPer100g: 31, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 55 }, { label: '1 cup', g: 110 }] },
  { name: 'Asparagus', caloriesPer100g: 20, category: 'Fruits & Vegetables', servings: [{ label: '5 spears', g: 80 }, { label: '10 spears', g: 160 }] },
  { name: 'Zucchini', caloriesPer100g: 17, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 62 }, { label: '1 cup', g: 124 }] },
  { name: 'Mushrooms', caloriesPer100g: 22, category: 'Fruits & Vegetables', servings: [{ label: '½ cup', g: 48 }, { label: '1 cup', g: 96 }] },
  { name: 'Onion', caloriesPer100g: 40, category: 'Fruits & Vegetables', servings: [{ label: '¼ cup', g: 40 }, { label: '½ cup', g: 80 }] },
  { name: 'Garlic', caloriesPer100g: 149, category: 'Fruits & Vegetables', servings: [{ label: '1 clove', g: 3 }, { label: '3 cloves', g: 9 }] },

  // Fats & Oils
  { name: 'Olive Oil', caloriesPer100g: 884, category: 'Fats & Oils', servings: [{ label: '1 tsp', g: 5 }, { label: '1 tbsp', g: 14 }] },
  { name: 'Coconut Oil', caloriesPer100g: 862, category: 'Fats & Oils', servings: [{ label: '1 tsp', g: 5 }, { label: '1 tbsp', g: 14 }] },
  { name: 'Vegetable Oil', caloriesPer100g: 884, category: 'Fats & Oils', servings: [{ label: '1 tsp', g: 5 }, { label: '1 tbsp', g: 14 }] },
  { name: 'Peanut Butter', caloriesPer100g: 588, category: 'Fats & Oils', servings: [{ label: '1 tbsp', g: 16 }, { label: '2 tbsp', g: 32 }] },
  { name: 'Almond Butter', caloriesPer100g: 614, category: 'Fats & Oils', servings: [{ label: '1 tbsp', g: 16 }, { label: '2 tbsp', g: 32 }] },
  { name: 'Almonds', caloriesPer100g: 579, category: 'Snacks', servings: [{ label: '10 nuts', g: 14 }, { label: '1 oz', g: 28 }, { label: '¼ cup', g: 35 }] },
  { name: 'Walnuts', caloriesPer100g: 654, category: 'Snacks', servings: [{ label: '1 oz', g: 28 }, { label: '¼ cup', g: 29 }] },
  { name: 'Cashews', caloriesPer100g: 553, category: 'Snacks', servings: [{ label: '1 oz', g: 28 }, { label: '¼ cup', g: 32 }] },
  { name: 'Peanuts', caloriesPer100g: 567, category: 'Snacks', servings: [{ label: '1 oz', g: 28 }, { label: '¼ cup', g: 37 }] },
  { name: 'Mixed Nuts', caloriesPer100g: 607, category: 'Snacks', servings: [{ label: '1 oz', g: 28 }] },
  { name: 'Chia Seeds', caloriesPer100g: 486, category: 'Fats & Oils', servings: [{ label: '1 tbsp', g: 10 }, { label: '2 tbsp', g: 20 }] },
  { name: 'Flax Seeds', caloriesPer100g: 534, category: 'Fats & Oils', servings: [{ label: '1 tbsp', g: 10 }, { label: '2 tbsp', g: 20 }] },

  // Snacks
  { name: 'Potato Chips', caloriesPer100g: 536, category: 'Snacks', servings: [{ label: '1 oz', g: 28 }, { label: 'small bag', g: 43 }] },
  { name: 'Tortilla Chips', caloriesPer100g: 489, category: 'Snacks', servings: [{ label: '1 oz', g: 28 }, { label: 'small bag', g: 43 }] },
  { name: 'Popcorn (air-popped)', caloriesPer100g: 387, category: 'Snacks', servings: [{ label: '1 cup', g: 8 }, { label: '3 cups', g: 24 }] },
  { name: 'Rice Cakes', caloriesPer100g: 387, category: 'Snacks', servings: [{ label: '1 cake', g: 9 }, { label: '2 cakes', g: 18 }] },
  { name: 'Hummus', caloriesPer100g: 177, category: 'Snacks', servings: [{ label: '2 tbsp', g: 28 }, { label: '¼ cup', g: 62 }] },
  { name: 'Guacamole', caloriesPer100g: 150, category: 'Snacks', servings: [{ label: '2 tbsp', g: 28 }, { label: '¼ cup', g: 57 }] },
  { name: 'Salsa', caloriesPer100g: 36, category: 'Snacks', servings: [{ label: '2 tbsp', g: 30 }, { label: '¼ cup', g: 60 }] },
  { name: 'String Cheese', caloriesPer100g: 296, category: 'Snacks', servings: [{ label: '1 stick', g: 28 }] },
  { name: 'Protein Bar (Quest)', caloriesPer100g: 371, category: 'Snacks', servings: [{ label: '1 bar', g: 60 }] },
  { name: 'Granola Bar', caloriesPer100g: 471, category: 'Snacks', servings: [{ label: '1 bar', g: 47 }] },

  // Sweets
  { name: 'Dark Chocolate (70%)', caloriesPer100g: 598, category: 'Sweets', servings: [{ label: '1 square', g: 10 }, { label: '1 oz', g: 28 }] },
  { name: 'Milk Chocolate', caloriesPer100g: 535, category: 'Sweets', servings: [{ label: '1 square', g: 10 }, { label: '1 oz', g: 28 }] },
  { name: 'Ice Cream (vanilla)', caloriesPer100g: 207, category: 'Sweets', servings: [{ label: '½ cup', g: 66 }, { label: '1 cup', g: 132 }] },
  { name: 'Honey', caloriesPer100g: 304, category: 'Sweets', servings: [{ label: '1 tsp', g: 7 }, { label: '1 tbsp', g: 21 }] },
  { name: 'Maple Syrup', caloriesPer100g: 260, category: 'Sweets', servings: [{ label: '1 tbsp', g: 20 }] },
  { name: 'Cookie (chocolate chip)', caloriesPer100g: 488, category: 'Sweets', servings: [{ label: '1 cookie', g: 16 }, { label: '2 cookies', g: 32 }] },
  { name: 'Brownie', caloriesPer100g: 415, category: 'Sweets', servings: [{ label: '1 piece', g: 60 }] },
  { name: 'Donut (glazed)', caloriesPer100g: 452, category: 'Sweets', servings: [{ label: '1 donut', g: 60 }] },
  { name: 'Muffin (blueberry)', caloriesPer100g: 377, category: 'Sweets', servings: [{ label: 'small', g: 57 }, { label: 'large', g: 113 }] },

  // Beverages
  { name: 'Orange Juice', caloriesPer100g: 45, category: 'Beverages', servings: [{ label: '½ cup', g: 124 }, { label: '1 cup', g: 248 }] },
  { name: 'Apple Juice', caloriesPer100g: 46, category: 'Beverages', servings: [{ label: '½ cup', g: 124 }, { label: '1 cup', g: 248 }] },
  { name: 'Almond Milk (unsweetened)', caloriesPer100g: 15, category: 'Beverages', servings: [{ label: '½ cup', g: 122 }, { label: '1 cup', g: 244 }] },
  { name: 'Oat Milk', caloriesPer100g: 45, category: 'Beverages', servings: [{ label: '½ cup', g: 122 }, { label: '1 cup', g: 244 }] },
  { name: 'Soda (cola)', caloriesPer100g: 41, category: 'Beverages', servings: [{ label: '12 oz can', g: 355 }, { label: '1 cup', g: 240 }] },
  { name: 'Sports Drink (Gatorade)', caloriesPer100g: 23, category: 'Beverages', servings: [{ label: '8 oz', g: 240 }, { label: '20 oz bottle', g: 591 }] },
  { name: 'Coffee (black)', caloriesPer100g: 2, category: 'Beverages', servings: [{ label: '8 oz mug', g: 240 }, { label: '12 oz', g: 355 }] },
  { name: 'Latte (whole milk)', caloriesPer100g: 61, category: 'Beverages', servings: [{ label: 'small (8oz)', g: 227 }, { label: 'medium (12oz)', g: 340 }, { label: 'large (16oz)', g: 454 }] },
  { name: 'Beer (regular)', caloriesPer100g: 43, category: 'Beverages', servings: [{ label: '12 oz can', g: 355 }, { label: 'pint', g: 473 }] },
  { name: 'Wine (red)', caloriesPer100g: 85, category: 'Beverages', servings: [{ label: '5 oz glass', g: 148 }] },
  { name: 'Wine (white)', caloriesPer100g: 82, category: 'Beverages', servings: [{ label: '5 oz glass', g: 148 }] },
  { name: 'Vodka', caloriesPer100g: 231, category: 'Beverages', servings: [{ label: '1 shot', g: 44 }] },

  // Common meals / condiments
  { name: 'Caesar Salad (no dressing)', caloriesPer100g: 17, category: 'Fruits & Vegetables' },
  { name: 'Caesar Dressing', caloriesPer100g: 470, category: 'Fats & Oils', servings: [{ label: '1 tbsp', g: 15 }, { label: '2 tbsp', g: 30 }] },
  { name: 'Ranch Dressing', caloriesPer100g: 475, category: 'Fats & Oils', servings: [{ label: '1 tbsp', g: 15 }, { label: '2 tbsp', g: 30 }] },
  { name: 'Olive Oil & Vinegar Dressing', caloriesPer100g: 450, category: 'Fats & Oils', servings: [{ label: '1 tbsp', g: 14 }, { label: '2 tbsp', g: 28 }] },
  { name: 'Ketchup', caloriesPer100g: 101, category: 'Other', servings: [{ label: '1 tbsp', g: 17 }, { label: '2 tbsp', g: 34 }] },
  { name: 'Mustard', caloriesPer100g: 66, category: 'Other', servings: [{ label: '1 tsp', g: 5 }, { label: '1 tbsp', g: 16 }] },
  { name: 'Mayonnaise', caloriesPer100g: 680, category: 'Fats & Oils', servings: [{ label: '1 tbsp', g: 14 }, { label: '2 tbsp', g: 28 }] },
  { name: 'Soy Sauce', caloriesPer100g: 53, category: 'Other', servings: [{ label: '1 tbsp', g: 16 }] },
  { name: 'Hot Sauce', caloriesPer100g: 11, category: 'Other', servings: [{ label: '1 tsp', g: 5 }] },

  // Soups
  { name: 'Cream of Tomato Soup', caloriesPer100g: 51, category: 'Other', servings: [{ label: '½ cup', g: 120 }, { label: '1 cup', g: 240 }, { label: '1 can', g: 305 }] },
  { name: 'Chicken Noodle Soup', caloriesPer100g: 32, category: 'Other', servings: [{ label: '1 cup', g: 240 }, { label: '1 can', g: 305 }] },
  { name: 'Lentil Soup', caloriesPer100g: 66, category: 'Other', servings: [{ label: '1 cup', g: 240 }] },
  { name: 'Minestrone Soup', caloriesPer100g: 40, category: 'Other', servings: [{ label: '1 cup', g: 240 }] },
];

export function searchLocal(query) {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  const common = COMMON_FOODS.filter(f => f.name.toLowerCase().includes(q))
    .slice(0, 6)
    .map(f => ({ ...f, source: 'local' }));
  const hf = searchHelloFresh(query);
  return [...common, ...hf];
}
