// Curated common foods with reliable calorie data (per 100g unless noted)
export const COMMON_FOODS = [
  // Proteins
  { name: 'Chicken Breast (cooked)', caloriesPer100g: 165, category: 'Proteins' },
  { name: 'Chicken Thigh (cooked)', caloriesPer100g: 209, category: 'Proteins' },
  { name: 'Ground Beef 80/20 (cooked)', caloriesPer100g: 254, category: 'Proteins' },
  { name: 'Ground Beef 93/7 (cooked)', caloriesPer100g: 218, category: 'Proteins' },
  { name: 'Salmon (cooked)', caloriesPer100g: 208, category: 'Proteins' },
  { name: 'Tuna (canned in water)', caloriesPer100g: 116, category: 'Proteins' },
  { name: 'Shrimp (cooked)', caloriesPer100g: 99, category: 'Proteins' },
  { name: 'Tilapia (cooked)', caloriesPer100g: 128, category: 'Proteins' },
  { name: 'Pork Chop (cooked)', caloriesPer100g: 231, category: 'Proteins' },
  { name: 'Turkey Breast (cooked)', caloriesPer100g: 135, category: 'Proteins' },
  { name: 'Bacon (cooked)', caloriesPer100g: 541, category: 'Proteins' },
  { name: 'Egg (whole, large)', caloriesPer100g: 143, category: 'Proteins' },
  { name: 'Egg White', caloriesPer100g: 52, category: 'Proteins' },
  { name: 'Greek Yogurt (plain, 0%)', caloriesPer100g: 59, category: 'Dairy' },
  { name: 'Greek Yogurt (plain, 2%)', caloriesPer100g: 73, category: 'Dairy' },
  { name: 'Cottage Cheese (1%)', caloriesPer100g: 72, category: 'Dairy' },
  { name: 'Cottage Cheese (4%)', caloriesPer100g: 98, category: 'Dairy' },
  { name: 'Black Beans (cooked)', caloriesPer100g: 132, category: 'Proteins' },
  { name: 'Chickpeas (cooked)', caloriesPer100g: 164, category: 'Proteins' },
  { name: 'Lentils (cooked)', caloriesPer100g: 116, category: 'Proteins' },
  { name: 'Edamame', caloriesPer100g: 122, category: 'Proteins' },
  { name: 'Tofu (firm)', caloriesPer100g: 76, category: 'Proteins' },
  { name: 'Deli Turkey', caloriesPer100g: 104, category: 'Proteins' },
  { name: 'Deli Ham', caloriesPer100g: 107, category: 'Proteins' },

  // Dairy
  { name: 'Whole Milk', caloriesPer100g: 61, category: 'Dairy' },
  { name: '2% Milk', caloriesPer100g: 50, category: 'Dairy' },
  { name: 'Skim Milk', caloriesPer100g: 34, category: 'Dairy' },
  { name: 'Cheddar Cheese', caloriesPer100g: 402, category: 'Dairy' },
  { name: 'Mozzarella Cheese', caloriesPer100g: 280, category: 'Dairy' },
  { name: 'Parmesan Cheese', caloriesPer100g: 431, category: 'Dairy' },
  { name: 'Cream Cheese', caloriesPer100g: 342, category: 'Dairy' },
  { name: 'Butter', caloriesPer100g: 717, category: 'Fats & Oils' },
  { name: 'Yogurt (plain, whole)', caloriesPer100g: 61, category: 'Dairy' },
  { name: 'Whey Protein Powder', caloriesPer100g: 400, category: 'Proteins' },

  // Grains
  { name: 'White Rice (cooked)', caloriesPer100g: 130, category: 'Grains' },
  { name: 'Brown Rice (cooked)', caloriesPer100g: 123, category: 'Grains' },
  { name: 'Oatmeal (cooked)', caloriesPer100g: 71, category: 'Grains' },
  { name: 'Oats (dry)', caloriesPer100g: 389, category: 'Grains' },
  { name: 'White Bread', caloriesPer100g: 265, category: 'Grains' },
  { name: 'Whole Wheat Bread', caloriesPer100g: 247, category: 'Grains' },
  { name: 'Sourdough Bread', caloriesPer100g: 274, category: 'Grains' },
  { name: 'Bagel (plain)', caloriesPer100g: 270, category: 'Grains' },
  { name: 'English Muffin', caloriesPer100g: 227, category: 'Grains' },
  { name: 'Pasta (cooked)', caloriesPer100g: 158, category: 'Grains' },
  { name: 'Whole Wheat Pasta (cooked)', caloriesPer100g: 149, category: 'Grains' },
  { name: 'Quinoa (cooked)', caloriesPer100g: 120, category: 'Grains' },
  { name: 'Tortilla (flour, 10")', caloriesPer100g: 306, category: 'Grains' },
  { name: 'Tortilla (corn, 6")', caloriesPer100g: 218, category: 'Grains' },
  { name: 'Granola', caloriesPer100g: 471, category: 'Grains' },
  { name: 'Cereal (Cheerios)', caloriesPer100g: 375, category: 'Grains' },
  { name: 'Pancake (plain)', caloriesPer100g: 227, category: 'Grains' },
  { name: 'Waffle (plain)', caloriesPer100g: 291, category: 'Grains' },
  { name: 'Crackers (saltine)', caloriesPer100g: 421, category: 'Grains' },

  // Fruits & Vegetables
  { name: 'Banana', caloriesPer100g: 89, category: 'Fruits & Vegetables' },
  { name: 'Apple', caloriesPer100g: 52, category: 'Fruits & Vegetables' },
  { name: 'Orange', caloriesPer100g: 47, category: 'Fruits & Vegetables' },
  { name: 'Strawberries', caloriesPer100g: 32, category: 'Fruits & Vegetables' },
  { name: 'Blueberries', caloriesPer100g: 57, category: 'Fruits & Vegetables' },
  { name: 'Grapes', caloriesPer100g: 69, category: 'Fruits & Vegetables' },
  { name: 'Watermelon', caloriesPer100g: 30, category: 'Fruits & Vegetables' },
  { name: 'Mango', caloriesPer100g: 60, category: 'Fruits & Vegetables' },
  { name: 'Pineapple', caloriesPer100g: 50, category: 'Fruits & Vegetables' },
  { name: 'Avocado', caloriesPer100g: 160, category: 'Fruits & Vegetables' },
  { name: 'Broccoli', caloriesPer100g: 34, category: 'Fruits & Vegetables' },
  { name: 'Spinach', caloriesPer100g: 23, category: 'Fruits & Vegetables' },
  { name: 'Kale', caloriesPer100g: 49, category: 'Fruits & Vegetables' },
  { name: 'Romaine Lettuce', caloriesPer100g: 17, category: 'Fruits & Vegetables' },
  { name: 'Mixed Greens', caloriesPer100g: 20, category: 'Fruits & Vegetables' },
  { name: 'Baby Carrots', caloriesPer100g: 35, category: 'Fruits & Vegetables' },
  { name: 'Celery', caloriesPer100g: 16, category: 'Fruits & Vegetables' },
  { name: 'Cucumber', caloriesPer100g: 15, category: 'Fruits & Vegetables' },
  { name: 'Bell Pepper', caloriesPer100g: 31, category: 'Fruits & Vegetables' },
  { name: 'Tomato', caloriesPer100g: 18, category: 'Fruits & Vegetables' },
  { name: 'Cherry Tomatoes', caloriesPer100g: 18, category: 'Fruits & Vegetables' },
  { name: 'Sweet Potato (baked)', caloriesPer100g: 90, category: 'Fruits & Vegetables' },
  { name: 'Potato (baked)', caloriesPer100g: 93, category: 'Fruits & Vegetables' },
  { name: 'Corn (cooked)', caloriesPer100g: 96, category: 'Fruits & Vegetables' },
  { name: 'Green Beans', caloriesPer100g: 31, category: 'Fruits & Vegetables' },
  { name: 'Asparagus', caloriesPer100g: 20, category: 'Fruits & Vegetables' },
  { name: 'Zucchini', caloriesPer100g: 17, category: 'Fruits & Vegetables' },
  { name: 'Mushrooms', caloriesPer100g: 22, category: 'Fruits & Vegetables' },
  { name: 'Onion', caloriesPer100g: 40, category: 'Fruits & Vegetables' },
  { name: 'Garlic', caloriesPer100g: 149, category: 'Fruits & Vegetables' },

  // Fats & Oils
  { name: 'Olive Oil', caloriesPer100g: 884, category: 'Fats & Oils' },
  { name: 'Coconut Oil', caloriesPer100g: 862, category: 'Fats & Oils' },
  { name: 'Vegetable Oil', caloriesPer100g: 884, category: 'Fats & Oils' },
  { name: 'Peanut Butter', caloriesPer100g: 588, category: 'Fats & Oils' },
  { name: 'Almond Butter', caloriesPer100g: 614, category: 'Fats & Oils' },
  { name: 'Almonds', caloriesPer100g: 579, category: 'Snacks' },
  { name: 'Walnuts', caloriesPer100g: 654, category: 'Snacks' },
  { name: 'Cashews', caloriesPer100g: 553, category: 'Snacks' },
  { name: 'Peanuts', caloriesPer100g: 567, category: 'Snacks' },
  { name: 'Mixed Nuts', caloriesPer100g: 607, category: 'Snacks' },
  { name: 'Chia Seeds', caloriesPer100g: 486, category: 'Fats & Oils' },
  { name: 'Flax Seeds', caloriesPer100g: 534, category: 'Fats & Oils' },

  // Snacks
  { name: 'Potato Chips', caloriesPer100g: 536, category: 'Snacks' },
  { name: 'Tortilla Chips', caloriesPer100g: 489, category: 'Snacks' },
  { name: 'Popcorn (air-popped)', caloriesPer100g: 387, category: 'Snacks' },
  { name: 'Rice Cakes', caloriesPer100g: 387, category: 'Snacks' },
  { name: 'Hummus', caloriesPer100g: 177, category: 'Snacks' },
  { name: 'Guacamole', caloriesPer100g: 150, category: 'Snacks' },
  { name: 'Salsa', caloriesPer100g: 36, category: 'Snacks' },
  { name: 'String Cheese', caloriesPer100g: 296, category: 'Snacks' },
  { name: 'Protein Bar (Quest)', caloriesPer100g: 371, category: 'Snacks' },
  { name: 'Granola Bar', caloriesPer100g: 471, category: 'Snacks' },

  // Sweets
  { name: 'Dark Chocolate (70%)', caloriesPer100g: 598, category: 'Sweets' },
  { name: 'Milk Chocolate', caloriesPer100g: 535, category: 'Sweets' },
  { name: 'Ice Cream (vanilla)', caloriesPer100g: 207, category: 'Sweets' },
  { name: 'Honey', caloriesPer100g: 304, category: 'Sweets' },
  { name: 'Maple Syrup', caloriesPer100g: 260, category: 'Sweets' },
  { name: 'Cookie (chocolate chip)', caloriesPer100g: 488, category: 'Sweets' },
  { name: 'Brownie', caloriesPer100g: 415, category: 'Sweets' },
  { name: 'Donut (glazed)', caloriesPer100g: 452, category: 'Sweets' },
  { name: 'Muffin (blueberry)', caloriesPer100g: 377, category: 'Sweets' },

  // Beverages
  { name: 'Orange Juice', caloriesPer100g: 45, category: 'Beverages' },
  { name: 'Apple Juice', caloriesPer100g: 46, category: 'Beverages' },
  { name: 'Whole Milk', caloriesPer100g: 61, category: 'Beverages' },
  { name: 'Almond Milk (unsweetened)', caloriesPer100g: 15, category: 'Beverages' },
  { name: 'Oat Milk', caloriesPer100g: 45, category: 'Beverages' },
  { name: 'Soda (cola)', caloriesPer100g: 41, category: 'Beverages' },
  { name: 'Sports Drink (Gatorade)', caloriesPer100g: 23, category: 'Beverages' },
  { name: 'Coffee (black)', caloriesPer100g: 2, category: 'Beverages' },
  { name: 'Latte (whole milk)', caloriesPer100g: 61, category: 'Beverages' },
  { name: 'Beer (regular)', caloriesPer100g: 43, category: 'Beverages' },
  { name: 'Wine (red)', caloriesPer100g: 85, category: 'Beverages' },
  { name: 'Wine (white)', caloriesPer100g: 82, category: 'Beverages' },
  { name: 'Vodka', caloriesPer100g: 231, category: 'Beverages' },

  // Common meals
  { name: 'Caesar Salad (no dressing)', caloriesPer100g: 17, category: 'Fruits & Vegetables' },
  { name: 'Caesar Dressing', caloriesPer100g: 470, category: 'Fats & Oils' },
  { name: 'Ranch Dressing', caloriesPer100g: 475, category: 'Fats & Oils' },
  { name: 'Olive Oil & Vinegar Dressing', caloriesPer100g: 450, category: 'Fats & Oils' },
  { name: 'Ketchup', caloriesPer100g: 101, category: 'Other' },
  { name: 'Mustard', caloriesPer100g: 66, category: 'Other' },
  { name: 'Mayonnaise', caloriesPer100g: 680, category: 'Fats & Oils' },
  { name: 'Soy Sauce', caloriesPer100g: 53, category: 'Other' },
  { name: 'Hot Sauce', caloriesPer100g: 11, category: 'Other' },
];

export function searchLocal(query) {
  if (!query || query.length < 1) return [];
  const q = query.toLowerCase();
  return COMMON_FOODS.filter(f => f.name.toLowerCase().includes(q))
    .slice(0, 6)
    .map(f => ({ ...f, source: 'local' }));
}
