const S = [{ label: '1 serving', g: 100 }];
const hf = (name, cal) => ({ name, caloriesPer100g: cal, category: 'Meals', brand: 'HelloFresh', servings: S });

export const HELLOFRESH_FOODS = [
  hf('Crispy Chicken Milanese', 460),
  hf('Chicken Gyro Salad w/ Tzatziki Dressing, Heirloom Tomatoes, & Cucumber', 520),
  hf("Palak's South Indian Shrimp Curry w/ Coconut Milk & Basmati Rice", 565),
  hf('Thai Pork Stir-Fry w/ Green Beans & Bell Peppers over Rice', 670),
  hf('Curried Cauliflower & Potatoes w/ Green Peas', 405),
  hf('Korean Beef Bibimbap', 770),
  hf('Beefy Taco Casserole w/ Mixed Green Salad', 597),
  hf('Bangers & Cauliflower Mash w/ Onion Gravy', 608),
  hf('Brown Rice Bibimbap w/ Veggie Ribbons & Soy Ginger Sauce', 570),
  hf('Shrimp & Asparagus Risotto w/ Meyer Lemon & Parmesan', 580),
  hf("Sweet 'N' Savory Chicken Fried Rice w/ Pineapple, Carrots, & Peas", 630),
  hf('Chicken & Chorizo Paella w/ Sweet Peppers, Tomatoes, & Rosemary', 602),
  hf('Southwestern Steak Tacos w/ SunGold Kiwi & Avocado Salsa', 840),
  hf('Spring Greens Gnocchi w/ Asparagus, Peas, & a Creamy Tarragon Sauce', 540),
  hf('Cuban-Style Beef Picadillo w/ Red Beans & Rice', 742),
  hf('Indian Stuffed Peppers w/ Curried Beef & Garam Masala-scented Rice', 778),
  hf('Lean Mean Chicken & Greens w/ Rosemary Potatoes & Gremolata', 650),
  hf('Beef Rice Noodle Bowls w/ Carrots, Cucumber, & Peanut Sauce', 770),
  hf('Sausage & Broccolini Orecchiette', 869),
  hf('Beef Sizzle Stir-Fry w/ Bok Choy over Jasmine Rice', 560),
  hf('Easy As (Shepherd\'s) Pie w/ Caramelized Onions & Roasted Carrots', 676),
  hf('Chicken Satay Skewers w/ Peanut Sauce', 632),
  hf('One-Pot Sausage & Tortelloni Soup w/ Baby Spinach in a Tomato Broth', 520),
  hf('Shrimp Banh Mi Burger w/ Sriracha Mayo & Carrot Fries', 670),
  hf('Wasabi Lime Salmon over Soy-Simmered Rice w/ Baby Bok Choy', 660),
  hf('Maple-Glazed Pork Chops w/ a Sweet Potato Mash & Garlicky Green Beans', 710),
  hf('Hoisin Beef Stir Fry w/ Bok Choy, Snow Peas, & Bell Peppers', 666),
  hf('Wonder-ful Pasta in Tomato Cream Sauce', 630),
  hf('Pan-Seared Steak w/ Herb Butter, Roasted Potatoes, & Green Bean Saute', 639),
  hf('Tempura Fish Tacos w/ Avocado Crema & Cabbage-Radish Slaw', 814),
  hf('Tangy Beef Stir-Fry w/ Fresh Noodles & Broccoli', 586),
  hf('Shrimp & Chorizo Paella w/ Smoked Paprika, Tomato, & Peas', 662),
  hf('Cavatappi in a Tomato Cream Sauce', 630),
  hf('Balsamic Chicken Rustico w/ Provencal Roasted Roots Veggies', 500),
  hf('Rapid Maple Balsamic Chicken w/ Sweet Potatoes & Broccoli', 567),
  hf('Pineapple Pork Stir-Fry w/ Snow Peas & Bell Pepper over Jasmine Rice', 670),
  hf('Spicy Pork & Kale Soup w/ Udon Noodles, Ginger, & Thai Chili', 559),
  hf('Sweet Potato Chickpea Curry w/ Baby Spinach over Basmati Rice', 740),
  hf('Indian Stuffed Peppers Garam Masala-Spiced Chickpeas, Peas & Carrots', 625),
  hf('Orzo & Chorizo Casserole w/ Burst Tomatoes, Mozzarella, & Spinach', 764),
  hf('Herbed Chicken Over Zucchini Risotto w/ Shallot & Blistered Tomatoes', 510),
  hf('Cozy Chickpea & Egg Skillet w/ Shakshuka Spices & Feta Cheese', 660),
  hf('Pan-Roasted Chicken w/ Dijon Mushroom Sauce & Israeli Couscous', 500),
  hf('Chili Roasted Shrimp w/ Spinach-White Bean Saute, Feta, & Mint', 472),
  hf('Chickpea Tikka Masala w/ Basmati, Yogurt, & Cilantro', 634),
  hf('Shrimp Pad See Ew w/ Broccoli, Mushrooms, & Peanuts', 730),
  hf("Mario Batali's Spaghetti", 570),
  hf('Red Sauce Rigatoni w/ Veggie-Packed Meatballs & Basil', 790),
  hf('Pork, Eggplant, & Squash Stir-Fry w/ Sesame & Ginger over Brown Rice', 710),
  hf('Crispy-Top Parmesan Chicken', 520),
  hf('Chicken Meatballs & Gnocchi w/ Sage, Apple, & Parmesan', 636),
  hf('Meatloaf Balsamico w/ Green Beans & Mashed Sweet Potatoes', 600),
  hf('Italian Meatloaf w/ Roasted Green Beans, & Mashed Potatoes', 640),
  hf('Heirloom Tomato Flatbread w/ Prosciutto, Fresh Mozzarella & Pesto', 900),
  hf('Oven-Baked Corn & Tomato Risotto w/ Pancetta & Parmesan', 689),
  hf('Chicken & Spinach Salad w/ Cheesy Roasted Zucchini & Tomatoes', 585),
  hf('Warm Shrimp & Farro Salad w/ Green Beans, Sweet Bell Pepper, & Shallots', 431),
  hf('Berbere-Spiced Salmon w/ Summer Vegetable & Orzo Salad', 642),
  hf('Lemon Basil Shrimp Skewers w/ Orzo & Avocado Salad', 710),
  hf('Chicken Lo Mein w/ Carrots & Green Beans', 620),
  hf('Turkey Chiles Rellenos w/ Poblano Peppers & Chipotle Sauce', 660),
  hf('French Onion Soup Burger w/ Bechamel, Caramelized Onions, & Kale Chips', 880),
  hf("Za'atar-Crusted Grilling Cheese w/ Sumac Roasted Veggies", 510),
  hf('Cherry-Drizzled Pork Chops w/ Couscous Tomato Salad', 550),
  hf('Greek Flatbread w/ Olives, Feta & Artichokes', 739),
  hf('Jerk Chicken & Peach Skewers w/ Curried Rice Pilaf', 492),
  hf('Yogurt-Marinated Chicken w/ Rice Pilaf, Roasted Zucchini, & Cilantro', 590),
  hf('Shiitake Mushroom Ramen w/ Ginger-Leek Broth & Udon', 409),
  hf('Roasted Vegetable Quesadillas w/ Smoky Chipotle Mayo & Guacamole', 839),
  hf('Pork Fajitas w/ Blistered Peppers & Sour Cream', 620),
  hf('Mushroom Stroganoff w/ Mustard Greens & Dijon Mashed Potatoes', 436),
  hf('Spanish Cod & Chorizo w/ Crispy Oregano Potatoes & Sautéed Kale', 694),
  hf('Tunisian Freekeh Stew w/ Roasted Chickpeas & Greek Yogurt', 757),
  hf('Thai Pork Laarb Burger Cucumber-Mint Salad', 626),
  hf('Gnocchi Bolognese', 585),
  hf('Chicken Paillard w/ Herb Gremolata, Rosemary Potatoes, & Arugula Salad', 506),
  hf('Hunan Cumin Beef Stir-Fry w/ Red Cabbage over Jasmine Rice', 770),
  hf('A Caesar Salad to Rule Them All w/ Chicken, Romaine, & Ciabatta Crouton', 520),
  hf('Shrimp Taco Lettuce Wraps w/ Smoky Chipotle Beans, Charred Fajita Veggies', 524),
  hf('Glazed Teriyaki Chicken w/ Bok Choy & Coconut Rice', 676),
  hf('Pork & Thai Basil Stir-Fry', 690),
  hf('Mustard Pork Chops & Potato Rosti w/ Tender Green Beans', 550),
  hf('Roasted Cauliflower & Squash Tacos w/ Yogurt Crema', 578),
  hf('Roasted Pork w/ Balsamic Fig Sauce, Green Beans, & Rosemary Potatoes', 526),
  hf('Creamy Dill Chicken w/ Roasted Potatoes & Green Beans', 430),
  hf('Crispy Fish Tacos w/ Lime Carrot Slaw & Sour Cream', 680),
  hf('Pork & Chinese Eggplant Stir-Fry over Brown Rice', 566),
  hf('Smoky Chicken Tacos w/ Charred Corn, Sautéed Veggies, & Salsa Fresca', 613),
  hf('Peanut Pork Noodle Bowl w/ Bell Pepper & Carrots over Rice Vermicelli', 890),
  hf('Beef Burrito Night w/ Refried Beans, Queso Fresco, Peppers, & Onion', 690),
  hf('Vegetarian Paella w/ Sweet Peppers, Mushrooms, & Rosemary', 401),
  hf('Toasted Thai Rice Bowl w/ Shrimp, Sweet Corn, & Red Bell Pepper', 504),
  hf('Amazing Apricot Chicken', 490),
  hf('Herbed Chicken Cutlets', 630),
  hf('Sicilian Eggplant Stew w/ Herbed Pork & Garlicky Ciabatta', 558),
  hf('Cheesy Polenta Cakes w/ Kale Mushroom Hash & Eggs', 551),
  hf('Tuscan Kale Panzanella w/ Fresh Mozzarella & Roasted Rainbow Carrots', 722),
  hf("Emeril Lagasse's Herbed Dijon Chicken Breasts w/ Zucchini & Red Potatoes", 550),
  hf('Roasted Salmon w/ Crispy Potatoes, Burst Tomatoes, & Green Beans', 625),
  hf('Skillet Turkey Enchiladas w/ a Lime Radish Salad', 690),
  hf('Paprika-Rubbed Chicken w/ Barley, Tomato, & Avocado Salad', 533),
  hf('Tater-Topped Pot Pie w/ Chicken, Mushrooms, & Peas', 680),
  hf('One-Pan Pork Carnitas Tacos w/ Lettuce, Onion, & a Lime Crema', 790),
  hf('Lamb Meatball Pitas w/ Yogurt Sauce', 933),
  hf('Swedish Meatballs over Egg Noodles & Baby Portobellos', 813),
  hf('Turkish-Spiced Salmon w/ Blood Orange & Couscous Pilaf', 695),
  hf('Pork al Mojo w/ Cuban Rice & Beans', 850),
  hf('Pasta Swirls & Sauce', 900),
  hf('Butternut Squash Agnolotti', 630),
  hf('Buttered-Up Butternut Squash Risotto', 600),
  hf('Hearty Pork Chili', 730),
  hf('Tortelloni En Brodo', 670),
  hf('Spring Veggie Flatbread w/ Basil Pesto & Lemon', 671),
  hf('Baby Portobello & Orecchiette Primavera w/ Asparagus & Bell Peppers', 550),
  hf('Mega Meatball Marinara w/ Creamy Polenta, Zucchini, & Mozzarella Cheese', 662),
  hf('Crispy Baked Cod w/ Buttered Potatoes, Green Beans, & Corn on the Cob', 550),
  hf('Crantastic Turkey Burgers w/ Jammy Mayo & a Green Salad', 820),
  hf('Sautéed Shrimp & Collard Greens over Cheddar Grits', 458),
  hf('Kiwi Salsa & Steak Fajitas w/ Charred Bell Pepper & Onion', 770),
  hf('Winning Pork Medallions w/ Potatoes, Brussels Sprouts, & Tarragon Cream', 510),
  hf('One-Pot Italian Wedding Soup w/ Pork Meatballs & Kale', 680),
  hf('Shrimp Saganaki w/ Spicy Marinara, Feta, & Israeli Couscous', 580),
  hf('Cheesy Burrito Bake w/ Beef, Ranchero Beans, & Lime Crema', 746),
  hf('Ground Beef & Guacamole Tacos w/ Radishes & Bell Pepper', 740),
  hf('Chorizo, Egg, & Avocado Sandwich w/ a Chorizo Potato Onion Hash', 810),
  hf('Creamy Coconut Fish Curry w/ Yukon Potatoes, Sweet Peas, & Cilantro', 741),
  hf('Chicken & Artichoke Cassoulet w/ Herbed Breadcrumbs & Mozzarella', 734),
  hf('Zesty Corn & Red Bean Salad w/ Roasted Sweet Potato, Feta, & Tomatoes', 553),
  hf('Shrimp & Lemon Risotto', 644),
  hf('Beef Ragu Spaghetti', 800),
  hf('Moo Shu Pork Tacos w/ Stir-Fried Veggies & Hoisin Mayo', 690),
  hf('Turkey & Sage Tetrazzini w/ Sweet Peas, Mushrooms, & Parmesan Cream Sauce', 696),
  hf('Honey Mustard Salmon w/ Roasted Asparagus & Israeli Couscous Pilaf', 670),
  hf('Smoky Adobo Chicken Tacos w/ Mango Slaw & Lime Crema', 801),
  hf('Sweet & Sour Pork w/ Pineapple, Snow Peas, & Bell Pepper over Bulgur', 580),
  hf('Stuffed Zucchini Boats w/ Mushroom Duxelles, Quinoa, & Parmesan', 439),
  hf('Meatloaf A La Mom', 650),
  hf('Spring Asparagus & Shrimp Risotto', 533),
  hf('Feisty Shrimp Linguine', 540),
  hf('One-Pan Pesto Tortelloni Bake w/ Asparagus & Parmesan', 720),
  hf('Mighty Meatless Bolognese w/ Seitan & Tagliatelle Pasta', 720),
  hf('Quick Sausage Bolognese w/ Spinach, Spaghetti, & Parmesan', 847),
  hf('Fregula Sarda & Sweet Italian Sausage w/ Wilted Spinach & Baby Portobello', 650),
  hf('Pesto Flatbread (aka Posh Pizza) w/ Zucchini, Baby Broccoli, & Tomatoes', 670),
  hf('Rigatoni "a la Vodka" w/ Pancetta, Spinach, & Herby Breadcrumbs', 659),
  hf('Greek Eggplant Ragu w/ Herbed Couscous', 529),
  hf('Roasted Half-Chicken Dinner w/ Potato Wedges, Pearl Onions, & Carrots', 810),
  hf('Skillet Chicken Pot Pie w/ Homemade Biscuits & Thyme Gravy', 811),
  hf('Blackened Tilapia w/ Crispy Potatoes & Blistered Veggies', 399),
  hf('Lemony Shrimp Risotto w/ Roasted Zucchini', 590),
  hf('Chickpea-Powered Mediterranean Couscous w/ Roasted Veggies & Feta', 610),
  hf('Oven Roasted Chicken w/ Winter Veggies & Lemon Thyme Sauce', 672),
  hf('Shrimp Saganaki w/ Olive Tomato Sauce over Couscous', 610),
  hf('Honey Sesame Chicken Tenders w/ Broccoli over Jasmine Rice', 650),
  hf('Turkish-Spiced Salmon w/ Oranges & Couscous Pilaf', 710),
  hf('Thai Beef Satay w/ Crispy Broccoli, Peanut Sauce, & Jasmine Rice', 669),
  hf('Sweet & Sour Shrimp over Jasmine Rice', 469),
  hf('Teriyaki Salmon w/ Green Beans & Jasmine Rice', 740),
  hf('Chipotle Black Bean Tacos', 715),
  hf('Smoky Turkey & White Bean Chili w/ Rosemary, Oregano, & Sour Cream', 559),
  hf("Monster Mac 'N' Cheese", 540),
  hf('Mediterranean Baked Veggies', 540),
  hf('One-Pan Mushroom Ravioli Gratin', 520),
  hf('Sesame Honey Beef Stir-Fry', 710),
  hf('Wild Mushroom Ravioli', 511),
  hf('Spring Tortellini Gratin', 592),
  hf('Prosciutto-Wrapped Chicken Saltimbocca', 416),
  hf('Lasagna Penne Bake', 868),
  hf('Italian Meatloaf', 660),
  hf('Perfect Penne Bake', 763),
  hf('Lemony Shrimp Risotto', 569),
  hf('Italian Meatloaf w/ Sun-Dried Tomatoes, Roasted Green Beans, & Garlic', 664),
  hf('Pan-Seared Chicken & Orecchiette Primavera', 808),
  hf('Chicken Penne', 867),
  hf('Quick Sausage Bolognese', 891),
  hf('Baked Chicken Parmesan w/ DIY Marinara, Fresh Mozzarella & Rigatoni', 780),
  hf('Tomato Garlic Ragu w/ Spaghetti', 789),
  hf('Parmesan Crusted Tilapia w/ Parsley & Carrots', 539),
  hf('Creamy Pea & Asparagus Risotto w/ Goat Cheese, Walnuts & Mint', 562),
  hf('Eggplant & Sun-Dried Tomato Linguine', 710),
  hf('Chicken Marsala w/ Skillet Zucchini & Mushroom Pan-Sauce', 705),
  hf('Sicilian Farro Caponata w/ Eggplant, Roasted Red Pepper, & Fresh Mozzar', 620),
  hf('Herby Sausage Risotto w/ Tomato, Parmesan, & Parsley', 759),
  hf('Chicken Milanese w/ Pesto Green Beans & Creamy Parmesan Potatoes', 651),
  hf('Peach & Nectarine Orzo Salad w/ Feta, Cucumber, & Mint', 517),
  hf('Melt in the Middle Meatballs w/ Crispy Broccolini', 931),
  hf('Herby Sausage Risotto w/ Tomato, Parmesan Cheese, & Zucchini', 741),
  hf('Charred Scallion & Corn Flatbread w/ Summer Squash & Salsa Fresca', 640),
  hf('Tortellini Gratin w/ Tomato Basil Bolognese & Cheesy Breadcrumbs', 724),
  hf('Crispy Chicken Milanese w/ Roasted Butternut Squash & Tomatoes', 522),
  hf('Personal Pizzas w/ Prosciutto, Artichokes, & Fresh Mozzarella', 735),
  hf('Creamy Prosciutto Panini w/ Fresh Mozzarella Cheese, Basil, & Green Salad', 514),
  hf('Nectarine & Zucchini Panzanella w/ Mint, Arugula, & Fresh Mozzarella', 558),
  hf('Portobello & Orecchiette Primavera w/ Spring Veggies', 622),
  hf('Italian Sausage & Mushrooms w/ Israeli Couscous, Spinach, & Parmesan', 708),
  hf('Spring Asparagus, Pea & Mint Penne w/ Ricotta', 800),
  hf('Italian Sausage & Baby Broccoli Pasta w/ Oregano Gremolata & Parmesan', 737),
  hf('Crispy Sunchoke Salad w/ Kale, Mushrooms & Farro', 686),
  hf('Crispy Chicken w/ Brown-Butter Corn & Cucumber Tomato Salad', 450),
  hf('Seared Tuna w/ Thyme-Roasted Summer Veggies & Lemon Aioli', 445),
  hf('Rapid Crispy Shrimp Tacos w/ Crunchy Red Cabbage Slaw', 679),
  hf('Lobster Ravioli & Shrimp w/ Heirloom Tomatoes & Tarragon Cream Sauce', 550),
  hf('Char-Grilled Barbecue Chicken w/ Creamy Green Bean & Potato Salad', 540),
  hf('Pan-Seared Pork w/ Onion Gravy, Broccolini & Rosemary Mashed Potatoes', 563),
  hf('Beef Ragu Spaghetti w/ Zucchini & Italian Seasonings', 800),
  hf('Honey Mustard Chicken w/ Roasted Sweet Potatoes, Zucchini, & Onion', 530),
  hf('Herbed Lemon Chicken Caesar Salad w/ Tomatoes & Parmesan', 577),
  hf('Beef Tenderloin Skewers w/ Charred Sweet Corn & Chipotle-Lime Butter', 531),
  hf('Chopped Chicken Salad w/ Charred Veggies & Avocado-Lime Dressing', 464),
  hf('The Icon Burger w/ Crispy Zucchini Fries', 976),
  hf('Sassy Soy Chicken w/ Roasted Broccoli & Lime Peanut Sauce', 730),
  hf('Brioche Shrimp Rolls w/ Arugula Radish Salad', 496),
  hf('Pan-Roasted Chicken w/ Dijon Mushroom Sauce & Brown Rice', 589),
  hf('Pistachio-Crusted Chicken w/ Quinoa & Chopped Cucumber Jalapeño Salad', 585),
  hf('Hearty Steak & Potatoes w/ Balsamic-Cranberry Pan Sauce', 535),
  hf('Citrus Skillet Shrimp w/ Poblano, Olives, & Crispy Potatoes', 456),
  hf('Italian Ciabatta Cheeseburgers w/ Mozzarella, Onion, & Balsamic Greens', 790),
  hf('Juicy Lucy Burger w/ Tomato-Onion Jam & Arugula Salad', 840),
  hf('Sesame Shrimp w/ Ginger Scallion Rice & Crispy Green Beans', 550),
  hf('Feisty Shrimp Linguine In Fra Diavolo Sauce', 540),
  hf('Seitan Tacos El Diablo w/ Kiwi Salsa & Lime Crema', 640),
  hf('Greek Salad Flatbreads w/ Artichokes, Olives, & Feta', 630),
  hf("Cauliflower Pancetta Mac 'n' Cheese w/ Cavatappi & Scallions", 730),
  hf('Cherry-and-Balsamic-Glazed Pork Chops w/ Crispy Broccoli & Potatoes', 552),
  hf('Honey-Glazed Pork Tenderloin w/ Caramelized Sweet Potatoes & Crispy Greens', 604),
  hf('Citrusy Pork Tenderloin w/ Wild Rice & Kale', 700),
  hf('Mushroom Chicken Scallopini w/ Skillet Zucchini & Basmati Rice', 710),
  hf('New York Strip Steak w/ Truffled Mashed Potatoes & Green Beans', 810),
  hf('Risotto alla Tex-Mex w/ Corn, Bell Pepper, & Pepitas', 530),
  hf('One-Pot Tortilla Soup w/ Black Beans, Corn, & Bell Pepper', 740),
  hf('Holy Moly Spinach Artichoke Ravioli Baked in Pesto Cream Sauce', 580),
  hf('Sesame Teriyaki Beef w/ Baby Bok Choy', 500),
  hf('Roasted Red Peppers Stuffed w/ Ras El Hanout-Spiced Pork', 558),
  hf('Kale Chip Quinoa Bowl w/ Olives, Tomatoes, & Feta Cheese', 590),
  hf('Hawaiian Pizza w/ Prosciutto, Caramelized Pineapple, & Spiced Honey', 679),
  hf('Tarragon Chicken & Wheat Berry Salad w/ Radishes, Dried Cherries & Almonds', 647),
  hf('Skillet Chilaquiles w/ Adobo Black Beans, Pickled Radish, & Sour Cream', 636),
  hf('Blackened Fish Tacos w/ Caramelized Pineapple & Red Cabbage Slaw', 770),
  hf('Pork Stir-Fry w/ Sweet Peppers, Green Beans, & Mint', 530),
  hf('Mushroom Lo Mein w/ Fresh Udon Noodles', 459),
  hf('Red Rice Bowl w/ Mushrooms, Spinach, & Cabbage', 601),
  hf('Toasted Rice & Shrimp Bowl w/ Bell Peppers & Corn', 550),
  hf('Crispy Noodle & Veggie Stir Fry w/ Ginger-Garlic Sauce', 634),
  hf('Pork Teriyaki w/ Egg Noodles, Asparagus, & Sesame', 758),
  hf('Chicken Yakitori w/ Pan-Fried Chuka Soba & Green Beans', 721),
  hf('Korean-Style Beef w/ Broccoli, Ginger, & Jasmine Rice', 598),
  hf('Sweet Potato & Quinoa Bowl w/ Avocado, Almonds & Feta', 771),
  hf('Mexican Tortilla Stacks w/ Guacamole & Black Bean Salsa', 663),
  hf('Mushroom Quesadillas w/ Lemony Guacamole', 583),
  hf('Honey Lime Shrimp Tacos w/ Creamy Cabbage Slaw', 590),
  hf('Shrimp Gyozas w/ Edamame Succotash', 805),
  hf('Patatas Bravas & Crispy Artichokes w/ a Garlicky Aioli', 610),
  hf('Curried Veggie Biryani w/ Sweet Potato, Peas, & Herbs', 746),
  hf('Tilapia Provencale w/ Citrus & Herb Veggies', 510),
  hf('Sweet Potato Nicoise Salad w/ Lemon-Dijon Dressing', 577),
  hf('Sesame-Crusted Tofu w/ Spicy Peanut Butter Sauce & Garlic Bok Choy', 785),
  hf('Rosemary-Walnut Crusted Chicken w/ Roasted Potatoes & Mixed Green Salad', 689),
  hf('Pan-Seared Gnocchi', 480),
  hf('Fun-Day Fajita Bar', 800),
  hf('Speedy Chili Shrimp Stir-Fry', 680),
  hf('Sizzling Southwestern Chicken', 560),
  hf('Apple Sage Turkey Burger', 770),
  hf('Lobster Ravioli & Shrimp', 580),
  hf('Creepy Crawly Tagliatelle Pasta', 430),
  hf('Creamy Dill Chicken', 430),
  hf('Phantom Tortelloni Bolognese', 870),
  hf('Pancetta Penne in a Witch\'s Cauldron', 730),
  hf('Chicken Parm Salad', 540),
  hf('Figgy Balsamic Port', 550),
  hf('Turkey Chiles Rellenos', 660),
  hf('Melty Monterey Jack Burger', 840),
  hf('Adobo Loco Steak', 600),
  hf('Meatloaf Balsamico', 640),
  hf('Seitan Tacos al Pastor', 610),
  hf('Southwestern Stuffed Pepper', 770),
  hf('Parmesan Chicken Tenders', 660),
  hf('Pork Luau Burger', 800),
  hf('Tomato-y Tortelloni Soup', 510),
  hf('Pineapple Pork Chops', 530),
  hf('Super Soy Chicken Tender', 670),
  hf('Italian Herbed Steak', 490),
  hf('Crispy Mozzarella Chicken', 590),
  hf('One-Pan Ravioli Gratin', 526),
  hf('One-Pan Orzo Italiano', 610),
  hf('Tortellini Gratin', 771),
  hf('Sliced Steak Tagliata', 530),
  hf('Italian Ciabatta Burger', 680),
  hf('Panko Parm Poulet w/ Potatoes', 540),
  hf('Presto Pesto Panko Chicken w/ a Green Salad & Roasted Potatoes', 610),
  hf('Lasagna-Baked Fusilli', 880),
  hf('Mozzarella-Crusted Chicken', 581),
  hf('Herby Pan-Seared Chicken', 618),
  hf('Fusilloni al Forno', 916),
  hf('Penne Arrabbiata', 577),
  hf('Hearty Steak & Potatoes', 535),
  hf('Steak Tagliata', 577),
  hf('Herbed Sirloin Steak', 790),
  hf('Herbs de Provence Chicken', 620),
  hf('Baked Fusilli Pasta', 900),
  hf('Creamy Poblano Bolognese', 799),
  hf('Cheesy Chorizo Orzotto', 790),
  hf('Rapid Butternut Squash Agnolotti', 638),
  hf('"Little Ears" Pasta w/ Broccoli & Pesto', 900),
  hf('Tomato-Garlic Ragu', 739),
  hf('Sweet Italian Sausage', 769),
  hf('Citrusy Shrimp Panzanella', 599),
  hf('Lemony Salmon & Cacio e Pepe Linguine w/ Crispy Broccoli & Tomatoes', 903),
  hf('Crispy Chicken Parmigiana Salad', 553),
  hf('Penne w/ a Kick', 600),
  hf('The Great Caper: Cod Piccata', 590),
  hf('Mushroom Chicken Scallopini', 710),
  hf('Chicken Sausage Pizza', 590),
  hf('One-Pot Italian Wedding Soup', 680),
  hf('Italian Sausage & Mushrooms', 741),
  hf('Butternut Squash Agnolotti w/ Apples, Spinach & Sage-Brown Butter Sauce', 490),
  hf('Pan-Seared Chicken & Orecchiette w/ Caramelized Bell Pepper & Parmesan', 764),
  hf('Tuscan Sausage Linguine w/ Zucchini, Chilies, & Parmesan', 862),
  hf('Speedy Italian Meatballs', 851),
  hf('Italian Sausage & Veggie Skewers', 870),
  hf('Beefed-Up Bolognese', 810),
  hf('Personal Pizza', 735),
  hf('Italian Sausage & Baby Broccoli Pasta', 767),
  hf('Orzo & Chorizo Casserole', 764),
  hf('Oven-Baked Corn & Tomato Risotto', 689),
  hf('Speedy Springtime Pasta w/ Mint, Pancetta & Peas', 730),
  hf('Heirloom Tomato Flatbread', 690),
  hf("Spicy Shrimp 'Fra Diavolo'", 608),
  hf('Heirloom Tomato Flatbread w/ Fresh Mozzarella, Pesto & Arugula', 753),
  hf('Sweet Italian Sausages & Blistered Tomatoes over Cheesy Kale Polenta', 690),
  hf('Roman Chicken w/ Mashed Potatoes', 589),
  hf('Pea & Asparagus Gnocchi w/ Tarragon & Brown Butter', 467),
  hf('Spaghetti w/ Saucy Beef Ragu w/ Zucchini & Italian Seasoning', 690),
  hf('Pesto Tortelloni Bake w/ Asparagus Parmesan', 700),
  hf('Gorgeous Green Farro Bowl w/ Asparagus & Zucchini', 520),
  hf('Caramelized Shallot Risotto w/ Lemony Zucchini Ribbons', 500),
  hf('One-Pot Tortelloni w/ Kale & Parmesan Breadcrumbs', 695),
  hf('Shrimp & Lemon Risotto w/ Roasted Zucchini & Parmesan', 569),
  hf('Herbed Sirloin Steak over Orzo Caprese Salad', 740),
  hf('Wild Mushroom Fettuccine', 599),
  hf('Italian Meatloaf w/ Green Beans & Garlicky Potatoes', 660),
  hf('Pea & Pancetta Penne w/ Parmesan, Pine Nuts, & Mint', 637),
  hf('Shrimp Farfalle w/ Fire Roasted Red Pepper, Lemon, & Basil', 646),
  hf('Italian Ciabatta Cheeseburgers w/ Mozzarella & Tangy Balsamic Greens', 730),
  hf('Tuscan Meatloaf w/ Roasted Green Beans & Rosemary Mashed Potatoes', 582),
  hf('Creamy Orecchiette w/ Brussels Sprouts, Pancetta, & Wild Mushrooms', 710),
  hf('No-Fuss Pesto Chicken w/ Potatoes & Green Salad', 680),
  hf('Spicy Chorizo & Tomato Penne w/ Charred Red Pepper', 715),
  hf('Seared Steak w/ Caprese Orzo Salad', 681),
  hf('Pillowy Parmesan Raviolini w/ Pesto & Veggie Medley', 620),
  hf('Tuscan Pork Linguine', 824),
  hf('Eggplant & Sun-Dried Tomato Linguine w/ Fresh Mozzarella & Chili', 720),
  hf('Chard & Wild Mushroom Penne', 611),
  hf('Italian Turkey Meatballs w/ Chive-Mashed Potatoes & Creamed Spinach', 523),
  hf('Tomato-Garlic Ragu w/ Beef, Parmesan, & Thyme', 724),
  hf('Lemony Shrimp Linguine w/ Roasted Red Pepper, Garlic, & Chili', 630),
  hf('Parmesan Raviolini w/ Pesto & Summer Vegetables', 661),
  hf('Quick Beef Ragu Spaghetti w/ Zucchini & Italian Seasoning', 740),
  hf('Roasted Butternut Squash & Leek Hash over Farro', 652),
  hf('Cannellini Bean Panzanella w/ Mozzarella, Cucumber, & Heirloom Tomatoes', 810),
  hf('Linguine & Zucchini w/ Sweet Italian Sausage in a Tomato Sauce', 830),
  hf('Tuscan Ribollita w/ Kale & Parmesan Croutons', 688),
  hf('One-Pan Tortelloni Gratin w/ Kale & Parmesan Breadcrumbs', 740),
  hf('Southwestern Tortellini Salad w/ Black Beans, Sweet Corn, & Cilantro', 847),
  hf('Italian Ciabatta Burgers w/ Mozzarella Cheese & Sweet-and-Tangy Salad', 725),
  hf('One-Pot Ravioli Bake w/ Spinach, Thyme, & Parmesan Breadcrumbs', 445),
  hf('Chicken Sausage Pizzas w/ Broiled Zucchini & Fresh Oregano', 570),
  hf('Tortellini En Brodo w/ Shredded Brussels Sprouts, Kale, & Parmesan', 610),
  hf('Crispy Chicken Parmigiana Salad w/ Potatoes & Spinach', 553),
  hf('Seared Sweet Italian Sausage w/ Warm Orzo Salad', 877),
  hf('Sausage & Warm Orzo Salad w/ Zucchini, Bell Pepper, & Tomatoes', 798),
  hf('Rigatoni Al Forno w/ Roasted Eggplant, Fresh Mozzarella, & Basil', 718),
  hf('Warm Grain Salad w/ Barley, Avocado & Burst Tomatoes', 753),
  hf('One-Pot Chicken Alfredo w/ Parmesan, Fresh Oregano, & Broccoli', 774),
  hf('Spring Tortellini Gratin w/ Asparagus & Parmesan Breadcrumbs', 592),
  hf('Perfect Penne Bake w/ Chicken Sausage & Kale', 760),
  hf('Cheesy Meatball Subs w/ Herby Marinara & Crispy Broccolini', 675),
  hf('Roasted Heirloom Tomato Flatbread w/ Pesto & Fresh Mozzarella Cheese', 582),
  hf('Burrata & Lemon Zest Ravioli w/ Shrimp & Zucchini Ribbons', 680),
  hf('One-Pan Orzo Italiano w/ Chicken Sausage, Tomatoes, & Spinach', 610),
  hf('Penne Arrabbiata w/ Pancetta, Chili, & Parmesan', 577),
  hf("Fusilloni 'al Forno' w/ Spinach, Homemade Marinara, & Fresh Ricotta", 786),
  hf('Swiss Chard & Wild Mushroom Penne w/ Chili & Parmesan', 632),
  hf('Parmesan Crusted Chicken w/ Tangy Balsamic Potato Salad', 575),
  hf('Florentine Stuffed Portobellos w/ Spinach & Sun-Dried Tomato', 641),
  hf('Warm Farro & Shrimp Bowl w/ Wax Beans, Sweet Bell Pepper & Shallot Citron', 606),
  hf("Mario Batali's Spaghetti w/ Fresh Tomatoes, Chorizo, & Basil", 570),
  hf('Quick-Marinated Steak w/ Balsamic-Glazed Summer Vegetables', 641),
  hf('NY Strip Steak w/ Balsamic Reduction over Polenta & Blistered Tomatoes', 740),
  hf('Pump Up The Jam Chicken & Pea-Almond Couscous', 800),
  hf('Bloody Mary Chicken w/ Pancetta & Pickled Red Onion', 597),
  hf('Dijon Pork Chops w/ Crispy Potato Cakes & Asparagus', 529),
  hf('Cavatappi in a Tomato Cream Sauce w/ Pancetta & Spinach', 690),
  hf('Italian Ciabatta Burgers w/ Caramelized Onion & Mozzarella', 914),
  hf('Catch of the Day: Cod Over Couscous w/ Citrus Dill Slaw', 597),
  hf('Chicken Pineapple Party Tacos w/ Bell Pepper & Fresh Radishes', 600),
  hf('Southern Pork Chops w/ Collard Green-Potato Hash & Black Pepper Gravy', 582),
  hf('Pork DIY Dumplings w/ Quick-Pickles Slaw & Soy Dumplings', 830),
  hf('Sweet Italian Sausage w/ Couscous & Spinach', 769),
  hf('Blackened Catfish w/ Crispy Potatoes & Blistered Summer Vegetables', 547),
  hf('Veggie-Loaded Orzo & Sausage w/ Lemon & Parmesan', 850),
  hf('Chipotle-Rubbed Chicken Salad w/ Pico de Gallo & Avocado', 808),
  hf('Creamy Mushroom Pork Chops w/ Roasted Brussels Sprouts & Crispy Potatoes', 597),
  hf('Caramelized-Pineapple Burgers w/ Monterey Jack Cheese & Red Cabbage Slaw', 769),
  hf('Pan-Seared Chicken w/ Peppercorn Sauce, Mashed Sweet Potato, & Roasted', 516),
  hf('Rapid Butternut Squash Agnolotti w/ Kale in a Sage Brown Butter Sauce', 638),
  hf('Thyme & Honey Pork Chops over Couscous w/ a Peachy Salad', 550),
  hf('Steak & Nectarine Salad w/ Spring Mix, Pecans, & Feta Cheese', 620),
  hf("Classic Poblano Beef Chili w/ Jack's Borlotti Beans", 777),
  hf('Spice-Rubbed Chicken w/ Sweet Potato, Bell Pepper, & Feta Jumble', 510),
  hf('Southwestern Stuffed Peppers w/ Beef, Quinoa, & Monterey Jack Cheese', 641),
  hf('One-Pan Shrimp Lo Mein w/ Udon Noodles, Green Beans, & Carrots', 510),
  hf('Upgraded Steak & Potatoes w/ Green Beans Amandine', 709),
  hf('Char-Broiled BBQ Chicken w/ Summery Potato & Green Bean Salad', 528),
  hf('Chicken & Nectarine Panzanella w/ Mint, Zucchini, & Fresh Mozzarella', 644),
  hf('Seared Steak & Charred Nectarine Salad w/ Feta, Pecans, & Basil', 659),
  hf('Butter-Basted Chicken w/ Peppery Potato Mash & Crispy Carrots', 672),
  hf('Caramelized Onion Burgers w/ Garlic Aioli & Crispy Cauliflower', 717),
  hf('Pesto Chicken Skewers w/ Tomato, Cucumber, & Corn Salad', 460),
  hf('Winner Winner Chicken Orzo Dinner w/ Cheesy Roasted Veggies', 727),
  hf('Roasted Pork Tenderloin w/ Lemony Potatoes & Zucchini', 550),
  hf('Chipotle-Glazed Pork Chops w/ Garlic Mashed Potatoes & Roasted Broccoli', 608),
  hf('Roasted Pork Tenderloin w/ Lemony Potato & Zucchini Hash', 434),
  hf('Chicken Paillard w/ Chimichurri, Sweet Potato Wedges, & Salad', 510),
  hf('Lemongrass Pork Burgers w/ Carrot Fries & Sriracha Mayo', 800),
  hf('Seared Steak w/ Spring Veggie Succotash & Mint-Chive Pesto', 489),
  hf('Serrano Steak w/ Mango Slaw & Cilantro-Lime Rice', 524),
  hf('Steak Tagliata w/ Rosemary Sweet Potato Wedges & Arugula Salad', 577),
  hf('Smoky Beef & Poblano Chili w/ Kidney Beans, Cheddar, & Sour Cream', 762),
  hf('Lemony Pan-Seared Chicken w/ Pesto Potato Salad & Peas', 531),
  hf('Rosemary Beef Skewers w/ Garlic Ciabatta & Charred Veggies', 560),
  hf('Sweet Pork Tenderloin & Apples w/ Cauliflower Mash & Snap Peas', 620),
  hf('Pan-Seared Chicken w/ Yukon Potatoes, Green Beans, & Creamy Dill Sauce', 449),
  hf('Monterey Jack Burger w/ Red Onion Marmalade & Crispy Zucchini Fries', 870),
  hf('The Pat LaFrieda Burger w/ Balsamic Onions & Crispy Cauliflower Oven Fries', 820),
  hf('Seared Steak & Nectarine Salad w/ Feta, Pecans, & Shallot Vinaigrette', 489),
  hf('Sweet-As-Honey Chicken w/ Snow Peas over Jasmine Rice', 510),
  hf('Crispy Spiced Chicken w/ Sweet Potato Fries & Garden Salad', 549),
  hf('Cherry Balsamic Pork Chops w/ Thyme-Roasted Potatoes & Broccoli', 610),
  hf('Parmesan-Crusted Cod w/ Herbed Potatoes & Carrots', 508),
  hf('Juicy Lucy Burger w/ Tomato-Onion Jam & Baby Gem Lettuce Salad', 825),
  hf('Chicken Cheddar Fajitas w/ Charred Bell Pepper & Lime Crema', 720),
  hf('Parmesan-Crusted Chicken w/ Balsamic Potato Salad & Garlic-Roasted Tomatoes', 532),
  hf('Very Teriyaki Pork Tenderloin w/ Basmati Rice & Asparagus', 620),
  hf('Melty Monterey Jack Burger w/ Red Onion Jam & Zucchini Fries', 860),
  hf('Peppercorn Steak w/ Crispy Roasted Potatoes & Creamed Kale', 647),
  hf('Chicken Paillard w/ Mustard Potato & Green Bean Salad', 541),
  hf('Chicken Parm Salad w/ Baby Spinach & a Creamy Lemon Dressing', 540),
  hf('Cherry-Drizzled Pork Chops w/ Couscous Salad', 560),
  hf('Chicken Pineapple Quesadillas w/ Pico de Gallo & Southwestern Spices', 660),
  hf('Zucchini & Parmesan-Crusted Chicken w/ Mashed Potatoes & Green Beans', 530),
  hf('Buttered-Up Steak w/ Roasted Potatoes & Garlicky Green Beans', 480),
  hf('Mozzarella-Crusted Chicken w/ Garlic-Roasted Tomatoes & Potato Wedges', 581),
  hf('Crushed Peppercorn Steak w/ Creamed Kale & Potato Wedges', 650),
  hf('Pineapple Pork Chops w/ Snap Peas & Jasmine Rice', 580),
  hf('Sriracha Turkey Burgers w/ Sweet Potato Chips & Ginger-Dressed Greens', 800),
  hf('Lasagna-Baked Fusilli w/ Kale & Mozzarella', 880),
  hf('Berbere Chicken & Zucchini w/ Cilantro Rice & Lemon Yogurt Sauce', 610),
  hf('Cumin-Spiced Steak w/ Scallion Dressing & Spinach Couscous Salad', 630),
  hf('Ginger Beef Stir-Fry w/ Snappy Asparagus', 610),
  hf('Mozzarella-Crusted Chicken w/ Blistered Tomatoes & Potato Wedges', 545),
  hf('Lean Green Steak Machine w/ a Mint Chive Dressing & Veggie Succotash', 500),
  hf('Panko Parm Poulet w/ Potatoes over Baby Spinach in a Creamy Lemon Dressing', 540),
  hf("Sweet 'N' Smoky Pork Chops w/ Sweet Potato Wedges & a Brussels Sprout Hash", 630),
  hf('Chicken Gone Nuts w/ a Walnut Crust, Glazed Carrots, & Roasted Broccoli', 570),
  hf('Shrimp & Cheddar Grits w/ Collard Greens & Tomatoes', 540),
  hf('Chicken Under a Zucchini Blanket w/ Mashed Potatoes & Green Beans', 630),
  hf('Butter-Basted Sirloin Steak w/ Parsnip Wedges & Creamed Spinach', 520),
  hf('Sliced Steak Tagliata w/ Sweet Potato Wedges & Warm Tomatoes in Vinaigrette', 530),
  hf('Wild Mushroom Ravioli w/ Grape Tomatoes, Zucchini, & Chili', 511),
  hf('Grilled Cheese & Veggie Jumble w/ Cilantro Chimichurri', 580),
  hf('Prosciutto-Wrapped Chicken Over Risotto Primavera', 730),
  hf('Cauliflower Pancetta Mac & Cheese', 736),
  hf('Parmesan-Crusted Chicken w/ Roasted Sweet Potato, Cranberry, & Arugula', 802),
  hf('Peppercorn Steak w/ Baby Potatoes & Creamed Spinach', 570),
  hf('Mozzarella & Pesto Crusted Chicken w/ Roasted Potatoes & Green Salad', 595),
  hf('When Steak Met Potatoes & Creamed Kale w/ Peppercorn Sauce', 525),
  hf('Bacon Apple Breakfast Flatbreads w/ Ricotta & Balsamic Onions', 640),
  hf('Crispy Cheddar Cheeseburger w/ Caramelized Onion Jam & Roasted Broccoli', 710),
  hf('Balsamic Onion Burgers w/ Crispy Cauliflower Oven Fries', 684),
  hf('Garlic Lime Chicken w/ Avocado Tomatillo Salsa', 640),
  hf('Crispy Salmon w/ Bok Choy, Wasabi Lime Dressing, & Soy-Infused Rice', 752),
  hf('Pork Luau Burgers w/ Pineapple Relish & Green Salad', 720),
  hf('Argentine-Spiced Steak w/ Couscous Salad & Cilantro-Scallion Chimichurri', 721),
  hf('Salmon En Papillote w/ Couscous Pilaf, Asparagus, & Tarragon Chive Sauce', 540),
  hf('Pan-Seared Salmon w/ Honeydew-Cucumber Salsa & Watercress Salad', 782),
  hf('Meatloaf A La Mom w/ Roasted Root Veggies & Thyme Gravy', 630),
  hf('Salsa Verde Sole w/ Roasted Potatoes & Green Beans', 520),
  hf('Penne w/ Sausage, Corn, & Zucchini On (or Off) the Grill', 840),
  hf("Carolina Barbecue Chicken w/ Stovetop Mac 'n' Cheese & Green Bean", 790),
  hf('Sesame Beef Stir Fry w/ Sugar Snap Peas & Basmati Rice', 675),
  hf('Country Gravy Pork Chops w/ a Potato & Collard Green Hash', 630),
  hf('Pork & Apple Burgers w/ Rosemary Fries & Mixed Greens', 738),
  hf('Jammy Fig & Brie Grilled Cheese w/ Arugula Mushroom Salad', 517),
  hf('The Great Caper: Cod Piccata w/ Couscous & Baby Spinach', 590),
  hf('Roasted Cauliflower Steaks w/ Bulgur, Tzatziki & Spiced Oil', 529),
  hf('Roasted Cauliflower w/ Bulgur, Tzatziki, & Chili Cumin Oil', 463),
  hf('Chopped Greek Salad w/ Cannellini Beans, Olives, & Toasted Pita', 572),
  hf('Greek Gyro Skewers w/ Roasted Zucchini, Baked Pita Chips, & Cucumber', 669),
  hf('Oven-Roasted Mediterranean Cauliflower w/ Bulgur, Tzatziki, & Chili', 460),
  hf('Honey-Roasted Squash w/ Warm Mushroom & Quinoa Salad', 484),
  hf('Creamy Bearnaise Strip Steak w/ Fingerling Potatoes & Sautéed Green Beans', 750),
  hf('Harissa Sweet Potato Pita Pockets w/ Cucumber-Dill Salad', 800),
  hf('Cumin Chimichurri Skirt Steak w/ a Summery Avocado & Charred Corn Salad', 880),
  hf('Arroz Con Pollo w/ Avocado, Tomato, & Lime Crema', 660),
  hf('BBQ-Rubbed Pork Chops w/ Spicy Plum Relish & Cilantro-Lime Forbidden Rice', 649),
  hf('Black Bean & Sweet Potato Bake w/ Feta, Jalapeno, & Tomato Salad', 547),
  hf('Crispy Chickpea Tacos w/ Guacamole & Roasted Vegetables', 781),
  hf('Breakfast Grilled Cheese Tacos w/ Avocado, Sweet Potato, & Tomato Salsa', 590),
  hf('Cheesy Chorizo Orzotto w/ Tomatoes & Spinach', 770),
  hf('Pork Larb over Jade Rice w/ Crispy Green Beans & Crushed Peanuts', 728),
  hf('Sweet Potato & Black Bean Tacos w/ Avocado Crema & Cilantro', 880),
  hf('Grilling Cheese Burgers w/ Broiled Summer Squash, Mint, & Lemon Aioli', 700),
  hf('Sugar-Rubbed Pork Chops w/ Caramelized Root Vegetables', 506),
  hf('Cheese-Filled Mediterranean Tacos w/ Roasted Zucchini, Cucumber & Tomato', 760),
  hf('Soy-Marinated Steak w/ Peanut Satay Sauce & Crispy Broccoli', 700),
  hf('Penne w/ a Kick in a Pancetta-Tomato Arrabbiata Sauce', 600),
  hf('Peach & Prosciutto Flatbread w/ Balsamic-Arugula Salad', 726),
  hf('Fajita Chicken Tenders Over Yellow Rice w/ Charred Baby Bell Peppers', 520),
  hf('Sriracha Turkey Lemongrass Skewers', 810),
  hf('Heirloom Tomato Flatbread w/ Prosciutto & Pesto', 690),
  hf('Mahi Mahi Piccata w/ Capers, Israeli Couscous Pilaf, & Sautéed Spinach', 662),
  hf('Panko-Crusted Cod w/ Wasabi Aioli, Quinoa, & Green Bean Tomato Saute', 674),
  hf('Italian Sausage & Veggie Skewers over Cheesy Herbed Orzo', 870),
  hf('Sriracha Turkey Burgers w/ Sweet Potato Crisps & Mixed Green Salad', 724),
  hf('Vegetarian Burrito Bowl w/ Salsa, Crispy Black Beans, & Monterey Jack', 561),
  hf('Orange-Glazed Meatballs w/ Crispy Broccolini & Rice', 581),
  hf('Protein-Packed Rice Bowl w/ Cashews, Sesame & Green Beans', 601),
  hf('Hoisin-Glazed Meatballs w/ Roasted Sweet Potato & Broccolini', 580),
  hf('Fiery Pork Fajitas w/ Blistered Peppers & Guacamole', 656),
  hf('Chimichurri Steak w/ Roasted Pepper, Tomato, & Couscous Salad', 624),
  hf('Sesame Beef Tacos w/ Quick-Pickled Veggies & Spicy Crema', 710),
  hf('Garden Quesadillas w/ Pico de Gallo & Chipotle Mayo', 593),
  hf('Soy-Glazed Steak w/ Wasabi Mashed Potatoes & Sesame Spinach', 751),
  hf('Citrusy Shrimp Panzanella w/ Tomatoes & Fresh Mozzarella', 599),
  hf('Chimichurri Burgers w/ Avocado, Monterey Jack, & Cabbage Slaw', 805),
  hf('Spanish-Style Spaghetti w/ Shrimp & Chorizo', 607),
  hf('Dukkah-Crusted Chicken w/ Sweet Potatoes & Sugar Snap Peas', 510),
  hf('Steak Fajitas w/ Kiwi Salsa & Crispy Beans', 895),
  hf('Feisty Fiesta Fish Tacos w/ Grapefruit, Avocado, & Cabbage Slaw', 659),
  hf('Smoky Beef Tacos w/ Peppers, Guacamole, & Radish', 736),
  hf('Herby Pan-Seared Chicken w/ Farro, Tomatoes, & Fresh Mozzarella', 600),
  hf('Pork Teriyaki w/ Basmati Rice & Asparagus', 657),
  hf('Honey Ginger Glazed Chicken w/ Snow Peas & Jasmine', 510),
  hf('White Sesame Teriyaki Beef w/ Bok Choy & Jasmine Rice', 494),
  hf('Spicy Pork & Kale Soup w/ Udon Noodles', 734),
  hf('Sesame Shrimp w/ Scallion Rice & Roasted Zucchini', 433),
  hf('Sweet-and-Sour Pork over Bulgur Wheat', 580),
  hf('Sweet & Sour Pork over Hearty Bulgur', 640),
  hf('Sriracha Turkey Lemongrass Skewers w/ Coconut Rice & Veggie Slaw', 810),
  hf('Toasted Rice Bowl w/ Shrimp, Sweet Corn, & Red Bell Pepper', 500),
  hf('Toasted Brown Rice Bowl w/ Green Beans, Carrots, & Cashews', 570),
  hf('Get Your Greens Rice Bowl w/ Bok Choy, Edamame, Asparagus, & Wasabi', 590),
  hf('Bok Choy & Black Rice Veggie Bowl w/ Marinated Radishes & Mushrooms', 500),
  hf('Wholesome Hoisin Veggie Stir-Fry w/ Snap Peas & Yellow Bell Pepper over', 480),
  hf('Hoisin Beef Stir-Fry w/ Baby Bok Choy over Jasmine Rice', 560),
  hf('Sizzling Hoisin Shrimp w/ Ginger Scallion Rice & Crispy Green Beans', 590),
  hf('Sriracha Sesame Wonton Pasta w/ Baby Broccoli & Edamame', 570),
  hf('Hoisin-Glazed Meatballs w/ Jasmine Rice & Snow Peas', 670),
  hf('Pork & Eggplant Stir-Fry over Brown Rice', 630),
  hf('Forbidden Rice Salad w/ Sugar Snap Peas, Beets & Mango', 518),
  hf('Korean-Style Beef Stir Fry w/ Broccolini, Brown Rice, & Sesame', 687),
  hf('Turkey Burrito Bake w/ Spinach, Black Beans, & Cheddar', 700),
  hf('Argentinean-Style Cod w/ Almond Herb Chimichurri', 576),
  hf('Spiced Chicken w/ Mexican Brown Rice & Bean Medley', 764),
  hf('Argentine Chimichurri Steak w/ a Sweet Potato, Poblano, & Tomato Jumble', 660),
  hf('Roasted Pepper Fajitas w/ Smoky Refried Beans & Citrus Sour Cream', 533),
  hf('Smoky Black Bean Cakes w/ Avocado Salsa & Tangy Arugula Salad', 594),
  hf('Cumin Quinoa Bowl w/ Black Beans, Bell Peppers, & Pepitas', 690),
  hf('Charred Zucchini & Bean Quesadillas w/ Fresh Romaine Salad & Lime Crema', 718),
  hf('Lemony Chicken Paillard w/ Sweet Potato Wedges & Arugula Salad', 506),
  hf('Pan-Seared Garlic Chicken w/ Crispy Broccoli & Potatoes Huancaina', 550),
  hf('Skillet Seitan Enchiladas w/ Poblano & Monterrey Jack', 792),
  hf('Peachy Pork Tacos w/ Tangy Summer Slaw', 699),
  hf('Beany Zucchini Quesadillas w/ Lime Crema, Romaine Salad, & Southwestern', 820),
  hf('Smoky Seitan Rice Bowl w/ Veggies & Guacamole', 660),
  hf('One-Pot Mexican Quinoa w/ Sweet Corn, Feta, & Jalapeño', 613),
  hf('Zucchini & Smoky Bean Quesadillas w/ Lime Sour Cream & Romaine Salad', 844),
  hf('Southwestern Black Bean Cakes w/ Avocado Salsa & Arugula', 580),
  hf('Southwestern Black Bean Chili w/ Cheddar & Sour Cream', 484),
  hf('One-Pan Hearty Pork Chili w/ Kidney Beans & Poblano Pepper', 830),
  hf('Turkey Taco Time w/ Poblano, Lime Crema, & Cheddar Cheese', 630),
  hf('Bell Pepper & Black Bean Quesadillas w/ an Arugula & Heirloom Tomato', 680),
  hf('Pineapple Poblano Beef Tacos w/ Lime Crema, Cilantro, & Warm Spices', 720),
  hf('One-Pot Mexican Quinoa w/ Sweet Corn, Avocado, & Feta', 777),
  hf('Black Bean & Charred Bell Pepper Quesadillas w/ Caramelized Onions', 786),
  hf('Cheesy Beef Quesadillas w/ Sour Cream & Avocado-Black Bean Salsa', 907),
  hf('Mole-Spiced Steak Tacos w/ Poblano & Mexican Corn Salad', 884),
  hf('Pescado Veracruz w/ Olive Ragout, Burst Tomatoes, & Basmati Rice', 467),
  hf('Roasted Veggie Tostadas w/ Tomato-Avocado Salsa', 793),
  hf('Skillet Chilaquiles w/ Chipotle, Black Beans & Radishes', 526),
  hf('Poblano & Portobello Fajitas w/ Fresh Guacamole', 739),
  hf('Mexican Quinoa Jumble w/ Pepitas, Charred Corn, & Feta', 543),
  hf('Smoky Chicken Fajitas w/ Blistered Corn Salsa & Fresh Guacamole', 705),
  hf('Charred Shrimp Skewers w/ Mexican Oregano & Pineapple-Avocado Salsa', 532),
  hf('Smoky Chicken Fajitas w/ Charred Pepper & Onions, w/ Lime Crema', 640),
  hf('Mushroom Lo Mein w/ Green Beans & Sweet Ginger Sauce', 460),
  hf('Honey Hoisin Beef w/ Baby Bok Choy over Jasmine Rice', 520),
  hf('Sizzling Beef Stir-Fry w/ Bok Choy over Jasmine Rice', 610),
  hf('Wasabi-Glazed Steak w/ Soba Noodle Salad & Creamy Avocado-Lime Dressing', 658),
  hf('Chicken Yakitori w/ Chuka Soba Stir-Fry', 805),
  hf('Chipotle Seitan Chili w/ Bell Pepper, Cheddar, & Jasmine Rice', 832),
  hf('Soba Noodle Stir-Fry w/ Corn, Mushrooms & Red Pepper', 518),
  hf('Spanish-Style Cod w/ Chickpeas over Zucchini & Arugula', 510),
  hf('Pan-Seared Calamari over Bulgur & Chorizo Hash w/ Parsley Gremolata', 724),
  hf('Spanish One-Pot Chicken & Rice w/ Chorizo, Sweet Peppers, & Lemon', 596),
  hf('Patatas Bravas Salad w/ Spicy Aioli, Almonds, & Feta', 588),
  hf('Spanish Steak Salad w/ Red Pepper & Roasted Garlic Vinaigrette', 764),
  hf('Spanish Steak Salad w/ Roasted Red Peppers & Rosemary-Garlic Vinaigrette', 701),
  hf("Chicken à l'Orange w/ Couscous", 795),
  hf('Oven-Roasted Cauliflower w/ Tunisian-Spiced Yogurt over Cumin-Scented Rice', 537),
  hf('Dukkah-Crusted Cod w/ Cranberry Couscous & Roasted Veggies', 580),
  hf("Waad's Tunisian Freekeh Stew w/ Crispy Chickpeas & Yogurt", 510),
  hf('Dukkah-Crusted Chicken w/ Sweet Potatoes & Snap Peas', 510),
  hf('Seared Chicken & Artichoke Pilaf w/ Spring Peas & Pan Sauce', 762),
  hf('Dukkah-Crusted Pork Chops w/ Mashed Potatoes & Lemony Greens', 594),
  hf('Tandoori Chicken w/ Julienned Apple Salad & Spiced Yogurt Sauce', 616),
  hf('Cod en Papillote w/ Brown Butter Caper-Sauce, Dill, & Red Pepper-Potato', 473),
  hf('Seared Provençal Steak w/ Three-Bean Salad', 599),
  hf('Lemon-Roasted Tilapia w/ Provencale Saute', 498),
  hf('Chicken Paillard w/ Rosemary Potatoes & Gremolata', 633),
  hf('Deconstructed Ratatouille w/ Balsamic Tomatoes, Feta, & Garlic Ciabatta', 636),
  hf('Summer Ratatouille w/ Fresh Tortelloni, Parmesan, & Basil', 554),
  hf('Loaded Lentil Salad w/ Honey-Roasted Sweet Potatoes & Brussels Sprouts', 612),
  hf('French Onion & Kale Soup w/ Gruyère Croutons', 515),
  hf('Purple Sweet Potato Nicoise w/ Black Olive Vinaigrette', 590),
  hf('Strip Steak Bearnaise w/ Creamed Kale & Rosemary Potatoes', 720),
  hf('Early Summer Potato Salad w/ Crispy Tofu, Dill & Tangy Dijon Dressing', 577),
  hf('Mushroom Gravy Chicken over Couscous w/ Lemony Arugula', 560),
  hf('Thai-Spiced Pork Meatballs w/ Yakisoba Noodles & Broccoli', 830),
  hf('Honey Lemongrass Chicken Legs over Jasmine Rice & Snow Peas', 900),
  hf('Coconut Shrimp Satay w/ Shaved Carrot & Cucumber Salad', 634),
  hf('Zesty Pork Chops w/ Summer Corn & Red Bean Salad', 547),
  hf('Queso Frito Rice w/ Grilling Cheese, Charred Poblanos, & Salsa Verde', 630),
];

export function searchHelloFresh(query) {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase();
  return HELLOFRESH_FOODS.filter(f => f.name.toLowerCase().includes(q))
    .slice(0, 5)
    .map(f => ({ ...f, source: 'local' }));
}
